# Generated by Django 2.1.7 on 2021-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField()),
                ('lno', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('ph', models.CharField(max_length=100)),
                ('qual', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=150)),
                ('exp', models.DateField()),
                ('hname', models.CharField(max_length=150)),
                ('cname', models.CharField(max_length=150)),
                ('dist', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('dp', models.ImageField(default=0, upload_to='profilepic/')),
                ('file', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('ph', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
