# Generated by Django 2.1.7 on 2021-03-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dprofile',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='dprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dprofile',
            name='dist',
        ),
        migrations.RemoveField(
            model_name='dprofile',
            name='hname',
        ),
        migrations.RemoveField(
            model_name='dprofile',
            name='state',
        ),
    ]
