# Generated by Django 2.1.7 on 2021-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0002_auto_20210330_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snacks')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('category', models.ManyToManyField(to='dietapp.Category')),
            ],
        ),
    ]
