# Generated by Django 2.1.7 on 2021-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0003_category_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFooditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ManyToManyField(blank=True, to='dietapp.user')),
                ('fooditem', models.ManyToManyField(to='dietapp.Fooditem')),
            ],
        ),
    ]
