# Generated by Django 2.1.7 on 2021-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0004_userfooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snacks')], default='k', max_length=50),
            preserve_default=False,
        ),
    ]
