# Generated by Django 2.1.7 on 2021-03-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0006_auto_20210330_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCaloryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('food1', models.CharField(max_length=60)),
                ('food2', models.CharField(max_length=60)),
                ('food3', models.CharField(max_length=60)),
                ('food4', models.CharField(max_length=60)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfooditem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userfooditem',
            name='fooditem',
        ),
        migrations.DeleteModel(
            name='UserFooditem',
        ),
    ]
